language: python

python:
    - "3.4"

install:
    - pip install codecov

script:
    - nosetests --with-coverage --cover-inclusive --cover-branches

branches:
    only:
        - master

after_success:
    - codecov
